version: "3"

services:

#  angular:
#    ports:
#      - 80:80
#    build: ./angular-service

#  spring-boot:
#    ports:
#      - 8080:8080
#    build: ./spring-boot-service

  mongodb:
    image: mongo
    ports:
      - 27017:27017