version: "3"

services:

  frontend-service:
    ports:
      - 80:80
    build: ./frontend-service


  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=kafka
    ports:
      - 2181:2181
      - 9092:9092


  travel-booking-service:
    ports:
      - 8080:8080
    build: ./travel-booking-service
    environment:
      - KAFKA_HOST=kafka
      - MONGO_HOST=travel-booking-service-db
      - MONGO_PORT=27017
  travel-booking-service-db:
    image: mongo


  flights-service:
    ports:
      - 3001:3000
    build: ./flights-service
    environment:
      - KAFKA_HOST=kafka
      - MONGO_HOST=flights-service-db
      - MONGO_PORT=27017
  flights-service-db:
    image: mongo


  hotels-service:
    ports:
      - 3002:3000
    build: ./hotels-service
    environment:
      - KAFKA_HOST=kafka
      - MONGO_HOST=hotels-service-db
      - MONGO_PORT=27017
  hotels-service-db:
    image: mongo