version: "3"

services:

#  angular:
#    ports:
#      - 80:80
#    build: ./angular-service

#  spring-boot:
#    ports:
#      - 8080:8080
#    build: ./spring-boot-service

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    network_mode: "host"

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=localhost
#      - ADVERTISED_HOST=kafka
    ports:
      - 2181:2181
      - 9092:9092
    network_mode: "host"